/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ActionButton {
    }
    interface BranchesTable {
        "branches": string;
    }
}
declare global {
    interface HTMLActionButtonElement extends Components.ActionButton, HTMLStencilElement {
    }
    var HTMLActionButtonElement: {
        prototype: HTMLActionButtonElement;
        new (): HTMLActionButtonElement;
    };
    interface HTMLBranchesTableElement extends Components.BranchesTable, HTMLStencilElement {
    }
    var HTMLBranchesTableElement: {
        prototype: HTMLBranchesTableElement;
        new (): HTMLBranchesTableElement;
    };
    interface HTMLElementTagNameMap {
        "action-button": HTMLActionButtonElement;
        "branches-table": HTMLBranchesTableElement;
    }
}
declare namespace LocalJSX {
    interface ActionButton {
    }
    interface BranchesTable {
        "branches"?: string;
    }
    interface IntrinsicElements {
        "action-button": ActionButton;
        "branches-table": BranchesTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "action-button": LocalJSX.ActionButton & JSXBase.HTMLAttributes<HTMLActionButtonElement>;
            "branches-table": LocalJSX.BranchesTable & JSXBase.HTMLAttributes<HTMLBranchesTableElement>;
        }
    }
}
